:- module(colors, [color/1]).

/** <module> Colors
Deze module bevat alle valide webkleuren, deze wordt gebruikt tijdens het parsen van de invoer.

@author Tibo Vanheule

*/

/**
 * color(-Arg:String)
 *
 * Predicate color, string is een valid webkleur.
 */
color(yellow).
color(yellowgreen).
color(white).
color(whitesmoke).
color(violet).
color(wheat).
color(turquoise).
color(tomato).
color(thistle).
color(teal).
color(tan).
color(steelblue).
color(springgreen).
color(snow).
color(slategrey).
color(slategray).
color(slateblue).
color(skyblue).
color(silver).
color(sienna).
color(seashell).
color(seagreen).
color(sandybrown).
color(salmon).
color(saddlebrown).
color(royalblue).
color(rosybrown).
color(red).
color(purple).
color(powderblue).
color(plum).
color(pink).
color(peru).
color(peachpuff).
color(papayawhip).
color(palevioletred).
color(paleturquoise).
color(palegreen).
color(palegoldenrod).
color(orchid).
color(orangered).
color(orange).
color(olive).
color(olivedrab).
color(oldlace).
color(navy).
color(navajowhite).
color(moccasin).
color(mistyrose).
color(mintcream).
color(midnightblue).
color(mediumvioletred).
color(mediumspringgreen).
color(mediumslateblue).
color(mediumseagreen).
color(mediumpurple).
color(mediumorchid).
color(mediumblue).
color(mediumaquamarine).
color(maroon).
color(magenta).
color(linen).
color(limegreen).
color(lime).
color(lightyellow).
color(lightsteelblue).
color(lightslategrey).
color(lightslategray).
color(lightskyblue).
color(lightpink).
color(lightseagreen).
color(lightsalmon).
color(lightgrey).
color(lightgray).
color(lightgreen).
color(lightgoldenrodyellow).
color(lightcyan).
color(lightcoral).
color(lightblue).
color(lemonchiffon).
color(lawngreen).
color(lavenderblush).
color(lavender).
color(khaki).
color(ivory).
color(indigo).
color(indianred).
color(hotpink).
color(honeydew).
color(grey).
color(greenyellow).
color(green).
color(gray).
color(goldenrod).
color(gold).
color(ghostwhite).
color(gainsboro).
color(fuchsia).
color(forestgreen).
color(floralwhite).
color(firebrick).
color(dodgerblue).
color(dimgrey).
color(dimgray).
color(deepskyblue).
color(deeppink).
color(darkviolet).
color(darkturquoise).
color(darkslategrey).
color(darkslategray).
color(darkslateblue).
color(darkseagreen).
color(darksalmon).
color(darkred).
color(darkorchid).
color(darkorange).
color(darkolivegreen).
color(darkmagenta).
color(darkkhaki).
color(darkgrey).
color(darkgreen).
color(darkgray).
color(darkgoldenrod).
color(darkcyan).
color(darkblue).
color(cyan).
color(crimson).
color(cornsilk).
color(cornflowerblue).
color(coral).
color(chocolate).
color(chartreuse).
color(cadetblue).
color(burlywood).
color(brown).
color(blueviolet).
color(blue).
color(blanchedalmond).
color(black).
color(bisque).
color(beige).
color(azure).
color(aquamarine).
color(aqua).
color(antiquewhite).
color(aliceblue).
